image: hashicorp/terraform:full

pipelines:
  default:
    - step:
        name: Format
        script:
          - terraform fmt -write=false -diff -check
    - step:
        name: Validate
        script:
          - mv main.tf.ci main.tf
          - mv terraform.tfvars.ci terraform.tfvars
          - terraform init
          - terraform validate
  custom:
    manual:
      - step:
          script:
            - apk update
            - apk upgrade
            - apk add --no-cache bash git grep
            - go get github.com/segmentio/terraform-docs
            - ./scripts/update_readme.sh
            - git status
            - git diff
