image: hashicorp/terraform:full

pipelines:
  default:
    - step:
        name: Check auto update
        script:
          - apk update
          - apk upgrade
          - apk add --no-cache bash git grep coreutils
          - go get github.com/segmentio/terraform-docs
          - ./scripts/auto_update.sh
          - git status
          - git diff --exit-code
